"""
Trajectory Planning Examples for Robotic Arm

This module contains various trajectory examples for the TrajectoryPlanner class.
Examples include geometric paths (linear, circular, square), parametric curves,
and pick-and-place operations with gripper control.

Usage:
    Run this script to see examples, or import trajectory functions into your own code.
"""

import numpy as np
from planner import TrajectoryPlanner
from kinematics import inverse_kinematics, direct_kinematics


# ============================================================================
# POLYLINE IMPORT FUNCTIONS
# ============================================================================

def load_polylines_from_file(file_path):
    """Load all polylines from a waypoints file generated by poly_extract.py.
    
    Args:
        file_path: Path to the waypoints file
        
    Returns:
        List of polylines, where each polyline is a list of (x, y, z) tuples
        Each polyline includes pen lift points at start and end.
    """
    polylines = []
    current_polyline = []
    last_line_was_coordinate = False
    
    with open(file_path, 'r') as f:
        for line in f:
            line = line.strip()
            
            # Skip comments
            if line.startswith('#'):
                continue
            
            # Empty line signals end of polyline
            if not line:
                if current_polyline:
                    polylines.append(current_polyline)
                    current_polyline = []
                last_line_was_coordinate = False
                continue
            
            # Parse coordinate line
            parts = line.split(',')
            if len(parts) == 3:
                try:
                    x = float(parts[0].strip())
                    y = float(parts[1].strip())
                    z = float(parts[2].strip())
                    current_polyline.append((x, y, z))
                    last_line_was_coordinate = True
                except ValueError:
                    continue
    
    # Add any remaining polyline
    if current_polyline:
        polylines.append(current_polyline)
    
    return polylines


def get_polyline_trajectory(file_path, polyline_index):
    """Get a specific polyline from a waypoints file as a trajectory function.
    
    Args:
        file_path: Path to the waypoints file
        polyline_index: Index of the polyline to extract (0-based)
        
    Returns:
        Tuple of (waypoint_list, T_duration) where:
        - waypoint_list: List of (x, y, z) tuples for the polyline (includes pen lift points)
        - T_duration: Suggested duration based on number of points
    """
    polylines = load_polylines_from_file(file_path)
    
    if polyline_index < 0 or polyline_index >= len(polylines):
        raise ValueError(f"Polyline index {polyline_index} out of range. File contains {len(polylines)} polylines.")
    
    waypoint_list = polylines[polyline_index]
    
    # Suggest duration based on number of points (rough estimate)
    T_duration = len(waypoint_list) * 0.02  # 20ms per waypoint
    
    return waypoint_list, T_duration


# ============================================================================
# CONFIGURATION
# ============================================================================

# Joint constraints
JOINTS_MAX_SPEEDS = np.array([20.0, 15.0, 15.0])  # deg/s
JOINTS_MAX_ACCEL = np.array([60.0, 20.0, 20.0])   # deg/s^2

# Mu function parameters (for variable end-effector orientation)
RMIN = 250
RMAX = 500
MUMIN = -90.0
MUMAX = -45.0

# Piece box coordinates (for pick & place with existing piece)
XBOX = 340.0
YBOX = -250.0
ZBOX = 110.0

# IK/FK wrappers
ik_func = lambda x, y, z, mu: [angle * 180.0/np.pi for angle in inverse_kinematics(x, y, z, mu=mu)]
fk_func = lambda theta, alpha, beta, gamma: direct_kinematics(
    theta * np.pi/180.0, alpha * np.pi/180.0, beta * np.pi/180.0, gamma * np.pi/180.0
)

# Mu function for variable end-effector orientation
def mu_func(x, y, z):
    """Calculate mu (end-effector orientation) based on distance from origin."""
    r = np.sqrt(x**2 + y**2)
    if r < RMIN:
        mu_deg = MUMIN
    elif r > RMAX:
        mu_deg = MUMAX
    else:
        mu_deg = MUMIN + (MUMAX - MUMIN) * (r - RMIN) / (RMAX - RMIN)
    return mu_deg * np.pi / 180.0  # Return radians


# ============================================================================
# GEOMETRIC TRAJECTORY FUNCTIONS
# ============================================================================

def linear_trajectory(t, T_total=3.0):
    """Straight line from start to end position."""
    s = t / T_total  # Normalized time [0, 1]
    x_start, y_start, z_start = 250, 0, 100
    x_end, y_end, z_end = 400, 200, 100
    
    x = x_start + (x_end - x_start) * s
    y = y_start + (y_end - y_start) * s
    z = z_start + (z_end - z_start) * s
    return [x, y, z]


def circular_trajectory(t, T_total=5.0):
    """Circle in XY plane at constant Z."""
    s = t / T_total  # Normalized time [0, 1]
    center_x, center_y, center_z = 350, 0, 50
    radius = 100
    angle = 2 * np.pi * s  # Full circle
    
    x = center_x + radius * np.cos(angle)
    y = center_y + radius * np.sin(angle)
    z = center_z
    return [x, y, z]


def square_trajectory(t, T_total=8.0):
    """Square path in XY plane at constant Z.
    
    Creates a square with 4 equal sides, moving counter-clockwise:
    - Segment 0 (t=0 to T/4): Bottom edge, left to right
    - Segment 1 (t=T/4 to T/2): Right edge, bottom to top
    - Segment 2 (t=T/2 to 3T/4): Top edge, right to left
    - Segment 3 (t=3T/4 to T): Left edge, top to bottom
    """
    s = t / T_total  # Normalized time [0, 1]
    center_x, center_y, center_z = (203+470)/2, 0, 10
    side_length = 470 - 203
    half_side = side_length / 2
    
    # Divide time into 4 segments (one per side)
    segment = int(s * 4)
    segment = min(segment, 3)  # Clamp to avoid index error at t=T_total
    local_s = (s * 4) - segment  # Progress within current segment [0, 1]
    
    if segment == 0:  # Bottom edge (left to right)
        x = center_x - half_side + side_length * local_s
        y = center_y - half_side
    elif segment == 1:  # Right edge (bottom to top)
        x = center_x + half_side
        y = center_y - half_side + side_length * local_s
    elif segment == 2:  # Top edge (right to left)
        x = center_x + half_side - side_length * local_s
        y = center_y + half_side
    else:  # Left edge (top to bottom)
        x = center_x - half_side
        y = center_y + half_side - side_length * local_s
    
    z = center_z
    return [x, y, z]


# ============================================================================
# PARAMETRIC CURVE TRAJECTORIES
# ============================================================================

def lissajous_curve(t, T_total=1.0):
    """Cool Lissajous curve pattern."""
    s = t / T_total
    return [
        400 + 40.0 * np.sin(5.0 * 2*np.pi*s),
        50.0 * np.cos(3.0 * 2*np.pi*s),
        15
    ]


def flower_curve_simple(t, T_total=1.0):
    """Simple flower-like parametric curve."""
    s = t / T_total
    return [
        500 + 25*(np.cos(16*np.pi*s) + 1/2*np.cos(6*np.pi*s) + 1/3*np.sin(10*np.pi*s)),
        25*(np.sin(16*np.pi*s) + 1/2*np.sin(6*np.pi*s) + 1/3*np.cos(10*np.pi*s)),
        20
    ]


def flower_curve_complex(t, T_total=1.0):
    """Complex flower curve using polar rose equations."""
    s = t * 38  # Scale time parameter
    return [
        500 + 3*(11*np.cos(s) - 6*np.cos(11*s/6)),
        3*(11*np.sin(s) - 6*np.sin(11*s/6)),
        18
    ]


# ============================================================================
# PICK & PLACE PRIMITIVES
# ============================================================================

def quarter_ellipse(s, xi, yi, zi, xf, yf, zf, n=3):
    """Quarter ellipse from (xi, yi, zi) to (xf, yf, zf).
    
    Args:
        s: Parameter from 0 to 1
        xi, yi, zi: Initial position
        xf, yf, zf: Final position
        n: Shape parameter (higher = more linear, lower = more curved)
    """
    s = 1-(1-s)**n if s>=0 else -1+(1+s)**n
    return [
        xi + (xf - xi) * s,
        yi + (yf - yi) * s,
        zf + (zi - zf) * (1 - abs(s)**n) ** (1/n)
    ]


def semi_ellipse(s, xi, yi, zi, xf, yf, zm, n=3):
    """Semi-ellipse arc from (xi, yi, zi) to (xf, yf, zi) with max height zm.
    
    Args:
        s: Parameter from 0 to 2 (half-ellipse spans two time units)
        xi, yi, zi: Initial position
        xf, yf: Final x, y position (z returns to zi)
        zm: Maximum Z height at the middle of the arc
        n: Shape parameter
    """
    s = s-1
    return quarter_ellipse(s, (xi+xf)/2, (yi+yf)/2, zm, xf, yf, zi, n=n)


# ============================================================================
# PICK & PLACE TRAJECTORIES
# ============================================================================

def pick_and_place_no_existing(t, xi=167, yi=0, zi=0, xp=203, yp=-132, zp=20, 
                               xg=470, yg=-132, zm=-50, n=3):
    """Pick & place: home -> pick piece -> place piece -> home.
    
    Timeline:
    - t=0 to 1: Home to piece location (quarter ellipse down)
    - t=1 to 3: Piece location to goal (semi-ellipse arc)
    - t=3 to 4: Goal to home (quarter ellipse up)
    
    Args:
        xi, yi, zi: Home position
        xp, yp, zp: Piece pick-up position
        xg, yg: Goal placement position (Z same as piece)
        zm: Minimum Z during transfer (for obstacle avoidance)
        n: Ellipse shape parameter
    """
    s = t
    if s <= 1: 
        return quarter_ellipse(s, xi, yi, zi, xp, yp, zp, n=n)
    if s <= 3: 
        return semi_ellipse(s-1, xp, yp, zp, xg, yg, zm, n=n)
    return quarter_ellipse(1-(s-3), xi, yi, zi, xg, yg, zp, n=n)


def pick_and_place_with_existing(t, xi=167, yi=0, zi=0, xp=203, yp=-132, zp=20,
                                xg=470, yg=-132, zm=-50, n=3):
    """Pick & place with existing piece removal: home -> goal -> box -> piece -> goal -> home.
    
    Timeline:
    - t=0 to 1: Home to goal (to remove existing piece)
    - t=1 to 2: Goal to box (discard existing piece)
    - t=2 to 3: Box to piece location (pick new piece)
    - t=3 to 5: Piece to goal (place new piece)
    - t=5 to 6: Goal to home
    
    Args:
        xi, yi, zi: Home position
        xp, yp, zp: Piece pick-up position
        xg, yg: Goal placement position
        zm: Minimum Z during transfer
        n: Ellipse shape parameter
    
    Note: Uses global XBOX, YBOX, ZBOX for discard box location
    """
    s = t
    if s <= 1: 
        return quarter_ellipse(s, xi, yi, zi, xg, yg, zp, n=n)
    if s <= 2: 
        return quarter_ellipse(1-(s-1), XBOX, YBOX, ZBOX, xg, yg, zp, n=n)
    if s <= 3: 
        return quarter_ellipse(s-2, XBOX, YBOX, ZBOX, xp, yp, zp, n=n)
    if s <= 5: 
        return semi_ellipse(s-3, xp, yp, zp, xg, yg, zm, n=n)
    return quarter_ellipse(1-(s-5), xi, yi, zi, xg, yg, zp, n=n)


# ============================================================================
# GRIPPER ACTION DEFINITIONS
# ============================================================================

GRIPPER_ACTIONS_PICK_PLACE = {
    0.0: 40.0,   # Start with gripper open
    1.0: 82.0,   # Close gripper (pick piece)
    3.0: 40.0,   # Open gripper (place piece)
}

GRIPPER_ACTIONS_WITH_REMOVAL = {
    0.0: 40.0,   # Start with gripper open
    1.0: 90.0,   # Close gripper (grab existing piece)
    2.0: 40.0,   # Open gripper (drop in box)
    3.0: 90.0,   # Close gripper (pick new piece)
    5.0: 40.0,   # Open gripper (place piece)
}


# ============================================================================
# EXAMPLE RUNNER FUNCTION
# ============================================================================

def run_example(trajectory_func, T_duration, gripper_actions=None, 
                n_waypoints=100, adaptive_sampling=False, use_mu_func=False):
    """Run a trajectory planning example.
    
    Args:
        trajectory_func: Function f(t) -> [x, y, z]
        T_duration: Duration of trajectory in normalized time units
        gripper_actions: Optional dict of time -> gripper angle
        n_waypoints: Number of waypoints to sample from trajectory
        adaptive_sampling: If True, sample more densely where acceleration is high
        use_mu_func: If True, use variable mu function; otherwise mu=0
    """
    # Create planner
    planner = TrajectoryPlanner(
        joints_max_speeds=JOINTS_MAX_SPEEDS,
        joints_max_accel=JOINTS_MAX_ACCEL,
        n_waypoints_input=n_waypoints,
        dt_sample=1e-3,
        inverse_kinematics_func=ik_func,
        mu_func=mu_func if use_mu_func else lambda x,y,z: 0,
        gripper_actions=gripper_actions,
        adaptive_sampling=adaptive_sampling
    )
    
    # Plan trajectory
    print(f"\n{'='*60}")
    print(f"Planning trajectory...")
    print(f"{'='*60}")
    planned_waypoints = planner.plan_trajectory(trajectory_func, T_duration)
    
    # Print summary
    print(f"\n{'='*60}")
    print("Generated Waypoints (Arduino format)")
    print(f"{'='*60}")
    time_us = round(planner.output_waypoint_dt * 1e6)
    output_parts = [f"wn{planner.output_waypoint_count}d{time_us}"]
    
    for waypoint in planned_waypoints:
        theta, alpha, beta, mu, gripper = waypoint
        waypoint_str = f"t{theta:.1f}a{alpha:.1f}b{beta:.1f}m{np.rad2deg(mu):.1f}g{gripper:.1f}"
        output_parts.append(waypoint_str)
    
    output = ",".join(output_parts)
    print(output)
    print(f"{'='*60}\n")
    
    # Show plots
    planner.plot_results(trajectory_func, T_duration)


def run_polyline_example(file_path, polyline_index, gripper_actions=None, 
                         use_mu_func=False):
    """Run a trajectory planning example using an imported polyline.
    
    Args:
        file_path: Path to waypoints file generated by poly_extract.py
        polyline_index: Index of the polyline to use (0-based)
        gripper_actions: Optional dict of normalized time (0 to 1) -> gripper angle
        use_mu_func: If True, use variable mu function; otherwise mu=0
    """
    # Load polyline
    waypoint_list, T_duration = get_polyline_trajectory(file_path, polyline_index)
    
    print(f"\n{'='*60}")
    print(f"Loaded polyline {polyline_index} from: {file_path}")
    print(f"Polyline contains {len(waypoint_list)} waypoints")
    print(f"Suggested duration: {T_duration:.2f}s")
    print(f"{'='*60}")
    
    # Create planner
    planner = TrajectoryPlanner(
        joints_max_speeds=JOINTS_MAX_SPEEDS,
        joints_max_accel=JOINTS_MAX_ACCEL,
        dt_sample=1e-3,
        inverse_kinematics_func=ik_func,
        mu_func=mu_func if use_mu_func else lambda x,y,z: 0,
        gripper_actions=gripper_actions
    )
    
    # Plan trajectory using waypoint list mode
    print(f"\n{'='*60}")
    print(f"Planning trajectory from waypoint list...")
    print(f"{'='*60}")
    planned_waypoints = planner.plan_trajectory(
        waypoint_list=waypoint_list,
        use_waypoint_list=True,
        gripper_actions=gripper_actions
    )
    
    # Print summary
    print(f"\n{'='*60}")
    print("Generated Waypoints (Arduino format)")
    print(f"{'='*60}")
    time_us = round(planner.output_waypoint_dt * 1e6)
    output_parts = [f"wn{planner.output_waypoint_count}d{time_us}"]
    
    for waypoint in planned_waypoints:
        theta, alpha, beta, mu, gripper = waypoint
        waypoint_str = f"t{theta:.1f}a{alpha:.1f}b{beta:.1f}m{np.rad2deg(mu):.1f}g{gripper:.1f}"
        output_parts.append(waypoint_str)
    
    output = ",".join(output_parts)
    print(output)
    print(f"{'='*60}\n")
    
    # Show plots (waypoint list mode doesn't have trajectory_func, so pass None)
    planner.plot_results(None, None)


# ============================================================================
# EXAMPLE SELECTION
# ============================================================================

if __name__ == "__main__":
    # Uncomment the example you want to run:
    
    # Example 1: Linear trajectory
    # run_example(
    #     trajectory_func=lambda t: linear_trajectory(t, T_total=3.0),
    #     T_duration=3.0
    # )
    
    # Example 2: Circular trajectory
    # run_example(
    #     trajectory_func=lambda t: circular_trajectory(t, T_total=5.0),
    #     T_duration=5.0
    # )
    
    # Example 3: Square trajectory
    # run_example(
    #     trajectory_func=lambda t: square_trajectory(t, T_total=8.0),
    #     T_duration=8.0
    # )
    
    # Example 4: Lissajous curve
    # run_example(
    #     trajectory_func=lambda t: lissajous_curve(t, T_total=1.0),
    #     T_duration=1.0,
    #     n_waypoints=200
    # )
    
    # Example 5: Simple flower curve
    # run_example(
    #     trajectory_func=lambda t: flower_curve_simple(t, T_total=1.0),
    #     T_duration=1.0,
    #     n_waypoints=200
    # )
    
    # Example 6: Complex flower curve
    # run_example(
    #     trajectory_func=lambda t: flower_curve_complex(t, T_total=1.0),
    #     T_duration=1.0,
    #     n_waypoints=200
    # )
    
    # Example 7: Pick & place (no existing piece)
    run_example(
        trajectory_func=lambda t: pick_and_place_no_existing(
            t, xi=100, yi=0, zi=100, 
            xp=470, yp=-132, zp=22, 
            xg=200, yg=132, zm=70, n=5
        ),
        T_duration=4.0,
        gripper_actions=GRIPPER_ACTIONS_PICK_PLACE,
        use_mu_func=True
    )
    
    # Example 8: Pick & place with existing piece removal
    # run_example(
    #     trajectory_func=lambda t: pick_and_place_with_existing(
    #         t, xi=167, yi=0, zi=0,
    #         xp=203, yp=-132, zp=-132,
    #         xg=470, yg=-132, zm=-50, n=3
    #     ),
    #     T_duration=6.0,
    #     gripper_actions=GRIPPER_ACTIONS_WITH_REMOVAL
    # )
    
    # Example 9: Import polyline from file
    # run_polyline_example(
    #     file_path="GUI/Draw/waypoints.txt",
    #     polyline_index=10,  # First polyline
    # )
